//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genbox.Presentation.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genbox.Presentation.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Enum_GuidGeneratorMode_Attribute {
            get {
                return ResourceManager.GetString("Enum_GuidGeneratorMode_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Define.
        /// </summary>
        public static string Enum_GuidGeneratorMode_ComDefine {
            get {
                return ResourceManager.GetString("Enum_GuidGeneratorMode_ComDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Implement.
        /// </summary>
        public static string Enum_GuidGeneratorMode_ComImplement {
            get {
                return ResourceManager.GetString("Enum_GuidGeneratorMode_ComImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Pattern.
        /// </summary>
        public static string Enum_GuidGeneratorMode_Pattern {
            get {
                return ResourceManager.GetString("Enum_GuidGeneratorMode_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        public static string Enum_GuidGeneratorMode_Structure {
            get {
                return ResourceManager.GetString("Enum_GuidGeneratorMode_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Enum_GuidGeneratorMode_Tag {
            get {
                return ResourceManager.GetString("Enum_GuidGeneratorMode_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string ServiceName_CollectionGenerator {
            get {
                return ResourceManager.GetString("ServiceName_CollectionGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string ServiceName_ConnectionStringGenerator {
            get {
                return ResourceManager.GetString("ServiceName_ConnectionStringGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string ServiceName_GuidGenerator {
            get {
                return ResourceManager.GetString("ServiceName_GuidGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ServiceName_PasswordGenerator {
            get {
                return ResourceManager.GetString("ServiceName_PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator 4 Developers.
        /// </summary>
        public static string Title_Application {
            get {
                return ResourceManager.GetString("Title_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Double similar to 420.
        /// </summary>
        public static double WindowWidth {
            get {
                object obj = ResourceManager.GetObject("WindowWidth", resourceCulture);
                return ((double)(obj));
            }
        }
    }
}
